jaffle_shop:
  target: dev # environment name, -t可以決定要用哪個環境
  outputs:
    dev: # environment name
      type: sqlite # ---> redshift

      # sqlite locks the whole db on writes so anything > 1 won't help
      threads: 1
      # host: localhost # 因為需要
      # port: 15439 # 開ssh
      # value is arbitrary
      database: "database" # specify database name for "use db_name"

      # value of 'schema' must be defined in schema_paths below. in most cases,
      # this should be 'main'
      schema: "main" # this is for postgre schema, prefix

      # connect schemas to paths: at least one of these must be 'main'
      schemas_and_paths:
        main: "db.sqlited" # sqlite的路徑, binary file

      # directory where all *.db files are attached as schema, using base filename
      # as schema name, and where new schema are created. this can overlap with the dirs of
      # files in schemas_and_paths as long as there's no conflicts.
      schema_directory: "/my_project/data"
